### ISSUE TITLE
Add-On Feedback

### ISSUE THREAD

**Issue by bhennes2** [LaunchPadLab/launchpad_api#3]
@francirp In following the README instructions, most things worked well. However, I needed to run `rake db:migrate` which I don't think was called out in the README.

Also, the README says Heroku Connect is optional so I didn't install it. After trying to load the API docs, I received a 500 error

<img width="1440" alt="Screen Shot 2019-10-28 at 10 05 00 PM" src="https://user-images.githubusercontent.com/597992/67734461-25d87500-f9cf-11e9-8208-2f33ecdc4777.png">

**Comment by francirp** [comment]
@bhennes2 got it - were there tables in the Postgres DB you used? The add-on is pointless without tables in a PG database, though I suppose it shouldn't "break" on install.

As for the DB migration, that's exactly the type of issue I was thinking could happen since my local setup probably already had that DB migrated. I'll see if I can recreate locally. Thanks man!

**Comment by francirp** [comment]
@bhennes2 the issues you identified have now been fixed. We will require at least one table mapping for the add-on to be installed. The API generation is useless without some type of DB table to generate an API against. The installation process now raises an error when tables aren't present.

**Comment by bhennes2** [comment]
@francirp What is the login to SF to configure HC?

**Comment by francirp** [comment]
@bhennes2 I've been using your login info to sign into a Salesforce account:

```
brendan@launchpadlab.com
launchpad1
```

**Comment by bhennes2** [comment]
@francirp I'm having trouble with my SF credentials and I don't want to be a blocker for you. If it's working for you, perhaps we put this back in SF's court and then do a small patch if we uncover any issues.
